import 'package:cloud_firestore/cloud_firestore.dart';

class Files16 {
  double budget;
  String fileid, clientid, clientname, filetype;
  int status,lockunlock;
  List<dynamic> sakkhi = [];
  List<dynamic> tofshil = [];
  List<dynamic> paspt = [];
  Timestamp date;
  String descriptionone,
      descriptiontwo,descriptionthree, descriptionfour,
      registryoffice,
      conpon,
      consompadonertarik,motmouaji,
      consonaktokarinaam,
      consonaktokaripitarnaam,
      consonaktokarimatarnaam,
      consonaktokarigram,
      consonaktokarizila,
      consonaktokaridakghor,
      consonaktokarithana,
      conchotushima8,
      conchotushima9,
      conchotushima10,
      conchotushima11,
      conchotushima12,
      conchotushima13,
      conchotushima14;
  Files16({
    required this.fileid,
    required this.clientid,
    required this.clientname,
    required this.filetype,
    required this.budget,
    required this.registryoffice,
    required this.status,
    required this.date,required this.paspt,
    required this.consonaktokarinaam,required this.motmouaji,
    required this.consonaktokaripitarnaam,
    required this.consonaktokarimatarnaam,
    required this.descriptionone,
    required this.descriptiontwo,
    required this.descriptionthree,
    required this.descriptionfour,
    required this.consonaktokarigram,
    required this.consompadonertarik,
    required this.consonaktokaridakghor,
    required this.consonaktokarithana,
    required this.consonaktokarizila,
    required this.conpon,
    required this.sakkhi,
    required this.tofshil,
    required this.lockunlock,
    required this.conchotushima8,
    required this. conchotushima9,
    required this. conchotushima10,
    required this. conchotushima11,
    required this. conchotushima12,
    required this. conchotushima13,
    required this. conchotushima14
  });

  Map<String, dynamic> toMap() => {
        'Files ID': fileid,
        'Client ID': clientid,
        'Client Name': clientname,
        'Description One': descriptionone,
        'Status': status,
        'Budget': budget,
        'Date': date,
        'Files Type': filetype,"Pasport 1st Party":paspt,
        'Description Two': descriptiontwo,
        'Registry Office Naam': registryoffice,
        'Sonaktokarir Naam': consonaktokarinaam,
        'Sonaktokarir Pitar Naam': consonaktokaripitarnaam,
        'Sonaktokarir Matar Naam': consonaktokarimatarnaam,
        'Sonaktokarir Village': consonaktokarigram,
        'Sonaktokarir Post Office': consonaktokaridakghor,
        'Sonaktokarir Thana': consonaktokarithana,
        'Sonaktokarir District': consonaktokarizila,
        'Shomprodaner Tarik': consompadonertarik,
    'Sakkhi': sakkhi,'Tofshil':tofshil,
    'Mot Mouaji':motmouaji,
     'Cotushima 8':conchotushima8,
    'Cotushima 9':conchotushima9,
    'Cotushima 10':conchotushima10,
   'Cotushima 11':conchotushima11,
    'Cotushima 12':conchotushima12,
    'Cotushima 13':conchotushima13,
    'Cotushima 14':conchotushima14,
        'Pon': conpon,
    'LockUnlock':lockunlock,
      };

  Files16.fromMap(Map<String, dynamic> maap)
      : fileid = maap['Files ID'],
        clientid = maap['Client ID'],
        clientname = maap['Client Name'],
        descriptionone = maap['Description One'],
        descriptionthree = maap['Description Three'],
        descriptionfour = maap['Description Four'],
        status = maap['Status'],
        consompadonertarik = maap['Shomprodaner Tarik'],
        conpon = maap['Pon'],
        budget = maap['Budget'],
        date = maap['Date'],
  paspt = maap["Pasport 1st Party"],motmouaji=maap["Mot Mouaji"],
  tofshil = maap['Tofshil'],
        lockunlock = maap["LockUnlock"],
        sakkhi = maap['Sakkhi'],
        conchotushima8 = maap['Cotushima 8'],
        conchotushima9 = maap['Cotushima 9'],
        conchotushima10 = maap['Cotushima 10'],
        conchotushima11 = maap['Cotushima 11'],
        conchotushima12 = maap['Cotushima 12'],
        conchotushima13 = maap['Cotushima 13'],
        conchotushima14 = maap['Cotushima 14'],
        registryoffice = maap['Registry Office Naam'],
        consonaktokarigram = maap['Sonaktokarir Village'],
        consonaktokaridakghor = maap['Sonaktokarir Post Office'],
        consonaktokarithana = maap['Sonaktokarir Thana'],
        consonaktokarizila = maap['Sonaktokarir District'],
        filetype = maap['Files Type'],
        descriptiontwo = maap['Description Two'],
        consonaktokarinaam = maap['Sonaktokarir Naam'],
        consonaktokaripitarnaam = maap['Sonaktokarir Pitar Naam'],
        consonaktokarimatarnaam = maap['Sonaktokarir Matar Naam'];
}
