import 'package:cloud_firestore/cloud_firestore.dart';

class Files14 {
  double budget;
  String fileid, clientid, clientname, filetype;
  int status,lockunlock;
  Timestamp date;
  List<dynamic> sakkhi = [];
  List<dynamic> mouaji1stparty = [];
  List<dynamic> mouaji2ndparty = [];
  String khomotapraptoatorny;
  String descriptionone,
      mullo,
      descriptiontwo,
      bbhumioffice,registryoffice,
      bsdage,
      englishdate,
      shoricannaam,
      shoricanpitarnaam,
      sadage,shoricansamirnaam,
      sompadonertarik,
      tofshildistrict1,
      imgurl,
      union,
      koifiot,
      tofshilThana2,
      tofshilupozila3,
      dolilnong,
      dolilertarik,
      tofshilmouja4,
      shreni,
      tofshiljlnoSA5,
      tofshiljaharBs6,
      tofshilSAkhotianNo7,
      tofshilNamzariKhotianNo8,
      tofshiljaharBSBujaritokhotiannumber9,
      tofshiljaharBSDP10,
      tofshiljaharBSchapa11,
      tofshilAdaagNo12,
      tofshiljaharBs13,
      tofshilMouaji14,
      tofshilchouhaddauttor,
      tofshilchouhaddadokshin,
      consonaktokarigram,
      consonaktokaridakghor,
      consonaktokarithana,
      consonaktokarizila,
      conflaterbiboron,
      gram,
      tofshilchouhaddapurba,
      tofshilchouhaddaposchim,
      consonaktokarinaam,
      consonaktokaripitarnaam,
      consonaktokarimatarnaam;

  Files14({
    required this.fileid,
    required this.clientid,
    required this.clientname,
    required this.filetype,
    required this.mullo,
    required this.budget,
    required this.bbhumioffice,
    required this.registryoffice,
    required this.koifiot,
    required this.imgurl,
    required this.union,
    required this.shreni,
    required this.status,
    required this.date,
    required this.sompadonertarik,
    required this.consonaktokarinaam,
    required this.conflaterbiboron,
    required this.bsdage,
    required this.sadage,
    required this.consonaktokaripitarnaam,
    required this.consonaktokarimatarnaam,
    required this.descriptionone,
    required this.descriptiontwo,
    required this.tofshiljaharBSchapa11,
    required this.consonaktokarigram,
    required this.khomotapraptoatorny,
    required this.consonaktokaridakghor,
    required this.consonaktokarithana,
    required this.consonaktokarizila,
    required this.tofshildistrict1,
    required this.tofshilThana2,
    required this.mouaji1stparty,
    required this.mouaji2ndparty,
    required this.tofshilupozila3,
    required this.gram,
    required this.tofshilmouja4,
    required this.tofshiljlnoSA5,
    required this.tofshiljaharBs6,
    required this.tofshilSAkhotianNo7,
    required this.tofshilNamzariKhotianNo8,
    required this.tofshiljaharBSBujaritokhotiannumber9,
    required this.tofshiljaharBSDP10,
    required this.tofshilAdaagNo12,
    required this.tofshiljaharBs13,
    required this.sakkhi,
    required this.tofshilMouaji14,
    required this.tofshilchouhaddauttor,required this.lockunlock,
    required this.tofshilchouhaddadokshin,
    required this.tofshilchouhaddapurba,
    required this.tofshilchouhaddaposchim,
    required this.dolilertarik,
    required this.dolilnong,
    required this.englishdate,
    required this.shoricannaam,
    required this.shoricanpitarnaam,
    required this.shoricansamirnaam,
  });

  Map<String, dynamic> toMap() => {
        'Files ID': fileid,
        'Client ID': clientid,
        'Client Name': clientname,
        'Description One': descriptionone,
        'Status': status,
        'Budget': budget,
        'Date': date,
        'Koifiot': koifiot,
        'Files Type': filetype,
        'Flater Biboron': conflaterbiboron,
        'Shorican Naam': shoricannaam,
        'Shorican PitarNaam': shoricanpitarnaam,
        'English Date': englishdate,
        'Description Two': descriptiontwo,
        'Tofshil Jahar BS Chapa 11': tofshiljaharBSchapa11,
        'Bhumi Office Naam': bbhumioffice,
    'Registry Office Naam': registryoffice,
        'Mullo': mullo,
    'Shorican SamirNaam': shoricansamirnaam,
        'Shomprodaner Tarik': sompadonertarik,
        'Noksha Image': imgurl,
        'Union': union,
        'Mouaji 1st Party': mouaji1stparty,
        'Dolil Nong': dolilnong,
        'Doliler Tarik': dolilertarik,
        'Mouaji 2nd Party': mouaji2ndparty,
        'Shreni': shreni,
        'Sonaktokarir Naam': consonaktokarinaam,
        'Sonaktokarir Pitar Naam': consonaktokaripitarnaam,
        'Sonaktokarir Matar Naam': consonaktokarimatarnaam,
        'Khomota Prapto Atorny': khomotapraptoatorny,
        'Sonaktokarir Village': consonaktokarigram,
        'Sonaktokarir Post Office': consonaktokaridakghor,
        'Sonaktokarir Thana': consonaktokarithana,
        'Sonaktokarir District': consonaktokarizila,
        'Tofshil District 1': tofshildistrict1,
        'Tofshil Thana 2': tofshilThana2,
        'Tofshil Upzila 3': tofshilupozila3,
        'Tofshil Mouja 4': tofshilmouja4,
        'Tofshil JLNO 5': tofshiljlnoSA5,
        'S A Dage': sadage,
        'B S Dage': bsdage,
        'Tofshil Jahar BS 6': tofshiljaharBs6,
        'Tofshil SA Khotian No 7': tofshilSAkhotianNo7,
        'Tofshil Namzari Khotian No 8': tofshilNamzariKhotianNo8,
        'Tofshil Jahar BS Bujarito 9': tofshiljaharBSBujaritokhotiannumber9,
        'Tofshil Jahar BSDP 10': tofshiljaharBSDP10,
        'Tofshil A Daag No 12': tofshilAdaagNo12,
        'Tofshil Jahar BS 13': tofshiljaharBs13,
        'Gram': gram,
        'Sakkhi': sakkhi,
    'LockUnlock':lockunlock,
        'Tofshil Mouaji 14': tofshilMouaji14,
        'Tofshil Chouhadda Uttor': tofshilchouhaddauttor,
        'Tofshil Chouhadda Dakshin': tofshilchouhaddadokshin,
        'Tofshil Chouhadda Purbo': tofshilchouhaddapurba,
        'Tofshil Chouhadda Poshim': tofshilchouhaddaposchim,
      };

  Files14.fromMap(Map<String, dynamic> maap)
      : fileid = maap['Files ID'],
        clientid = maap['Client ID'],
        clientname = maap['Client Name'],
        descriptionone = maap['Description One'],
        status = maap['Status'],
        tofshiljaharBSchapa11 = maap['Tofshil Jahar BS Chapa 11'],
        budget = maap['Budget'],
        dolilnong = maap['Dolil Nong'],
        dolilertarik = maap['Doliler Tarik'],
        date = maap['Date'],
        lockunlock = maap["LockUnlock"],
        koifiot = maap['Koifiot'], shoricansamirnaam=maap['Shorican SamirNaam'],
        mullo = maap['Mullo'],
        sadage = maap['S A Dage'],
        conflaterbiboron = maap['Flater Biboron'],
        shoricannaam = maap['Shorican Naam'],
        shoricanpitarnaam = maap['Shorican PitarNaam'],
        englishdate = maap['English Date'],
        bsdage = maap['B S Dage'],
        gram = maap['Gram'],
        bbhumioffice = maap['Bhumi Office Naam'],
  registryoffice = maap['Registry Office Naam'],
        imgurl = maap['Noksha Image'],
        sompadonertarik = maap['Shomprodaner Tarik'],
        sakkhi = maap['Sakkhi'],
        union = maap['Union'],
        shreni = maap['Shreni'],
        consonaktokarigram = maap['Sonaktokarir Village'],
        consonaktokaridakghor = maap['Sonaktokarir Post Office'],
        consonaktokarithana = maap['Sonaktokarir Thana'],
        consonaktokarizila = maap['Sonaktokarir District'],
        mouaji1stparty = maap['Mouaji 1st Party'],
        mouaji2ndparty = maap['Mouaji 2nd Party'],
        khomotapraptoatorny = maap['Khomota Prapto Atorny'],
        filetype = maap['Files Type'],
        descriptiontwo = maap['Description Two'],
        tofshildistrict1 = maap['Tofshil District 1'],
        tofshilThana2 = maap['Tofshil Thana 2'],
        tofshilupozila3 = maap['Tofshil Upzila 3'],
        tofshilmouja4 = maap['Tofshil Mouja 4'],
        tofshiljlnoSA5 = maap['Tofshil JLNO 5'],
        tofshiljaharBs6 = maap['Tofshil Jahar BS 6'],
        tofshilSAkhotianNo7 = maap['Tofshil SA Khotian No 7'],
        tofshilNamzariKhotianNo8 = maap['Tofshil Namzari Khotian No 8'],
        consonaktokarinaam = maap['Sonaktokarir Naam'],
        consonaktokaripitarnaam = maap['Sonaktokarir Pitar Naam'],
        consonaktokarimatarnaam = maap['Sonaktokarir Matar Naam'],
        tofshiljaharBSBujaritokhotiannumber9 =
            maap['Tofshil Jahar BS Bujarito 9'],
        tofshiljaharBSDP10 = maap['Tofshil Jahar BSDP 10'],
        tofshilAdaagNo12 = maap['Tofshil A Daag No 12'],
        tofshiljaharBs13 = maap['Tofshil Jahar BS 13'],
        tofshilMouaji14 = maap['Tofshil Mouaji 14'],
        tofshilchouhaddauttor = maap['Tofshil Chouhadda Uttor'],
        tofshilchouhaddadokshin = maap['Tofshil Chouhadda Dakshin'],
        tofshilchouhaddapurba = maap['Tofshil Chouhadda Purbo'],
        tofshilchouhaddaposchim = maap['Tofshil Chouhadda Poshim'];
}
