import 'package:cloud_firestore/cloud_firestore.dart';

import 'generalinfoModel.dart';

class Files8 {
  double budget;
  String fileid, clientid, clientname, filetype;
  int status,lockunlock;
  Timestamp date;
  String descriptionone,
      descriptiontwo,
      tofshildistrict1,
      tofshilThana2,
      tofshilupozila3,
      tofshilmouja4,
      tofshiljlnoSA5,
      tofshiljaharBs6,
      bhumioffice,
      tofshilSAkhotianNo7,
      tofshilNamzariKhotianNo8,
      tofshiljaharBSDP9,
      tofshilAdaagNo10,
      tofshiljaharBSchapa11,
      tofshiljaharBs12,
      tofshilMouaji13,
      tofshilchouhaddauttor,
      tofshilchouhaddadokshin,
      tofshilchouhaddapurba,
      tofshilchouhaddaposchim;

  Files8(
      {required this.fileid,
      required this.clientid,
      required this.clientname,
      required this.filetype,
      required this.budget,required this.lockunlock,
        required this.status,
        required this.date,
      required this.descriptionone,
      required this.descriptiontwo,
      required this.tofshildistrict1,
      required this.tofshilThana2,
      required this.tofshilupozila3,
        required this.bhumioffice,
      required this.tofshilmouja4,
      required this.tofshiljlnoSA5,
      required this.tofshiljaharBs6,
      required this.tofshilSAkhotianNo7,
      required this.tofshilNamzariKhotianNo8,
      required this.tofshiljaharBSDP9,
      required this.tofshilAdaagNo10,
        required this.tofshiljaharBSchapa11,
      required this.tofshiljaharBs12,
      required this.tofshilMouaji13,
      required this.tofshilchouhaddauttor,
      required this.tofshilchouhaddadokshin,
      required this.tofshilchouhaddapurba,
      required this.tofshilchouhaddaposchim});

  Map<String, dynamic> toMap() {
    return {
      'Files ID': fileid,
      'Client ID': clientid,
      'Client Name': clientname,
      'Description One': descriptionone,
      'Status': status,
      'Budget': budget,
      'Date': date,
      'Files Type': filetype,
      'Registry Office Naam': bhumioffice,
      'Description Two': descriptiontwo,
      'Tofshil District 1': tofshildistrict1,
      'Tofshil Thana 2': tofshilThana2,
      'Tofshil Upzila 3': tofshilupozila3,
      'Tofshil Mouja 4': tofshilmouja4,
      'Tofshil JLNO 5': tofshiljlnoSA5,
      'LockUnlock':lockunlock,
      'Tofshil Jahar BS 6': tofshiljaharBs6,
      'Tofshil SA Khotian No 7': tofshilSAkhotianNo7,
      'Tofshil Namzari Khotian No 8': tofshilNamzariKhotianNo8,
      'Tofshil Jahar BSDP 9': tofshiljaharBSDP9,
      'Tofshil A Daag No 10': tofshilAdaagNo10,
      'Tofshil Jahar BS Chapa 11': tofshiljaharBSchapa11,
      'Tofshil Jahar BS 12': tofshiljaharBs12,
      'Tofshil Mouaji 13': tofshilMouaji13,
      'Tofshil Chouhadda Uttor': tofshilchouhaddauttor,
      'Tofshil Chouhadda Dakshin': tofshilchouhaddadokshin,
      'Tofshil Chouhadda Purbo': tofshilchouhaddapurba,
      'Tofshil Chouhadda Poshim': tofshilchouhaddaposchim,
    };
  }

  Files8.fromMap(Map<String, dynamic> maap)
      : fileid = maap['Files ID'],
        clientid = maap['Client ID'],
        clientname = maap['Client Name'],
        descriptionone = maap['Description One'],
        status = maap['Status'],
        budget = maap['Budget'],
        date = maap['Date'],
  lockunlock = maap["LockUnlock"],
        filetype = maap['Files Type'],
        bhumioffice = maap['Registry Office Naam'],
        descriptiontwo = maap['Description Two'],
        tofshildistrict1 = maap['Tofshil District 1'],
        tofshilThana2 = maap['Tofshil Thana 2'],
        tofshilupozila3 = maap['Tofshil Upzila 3'],
        tofshilmouja4 = maap['Tofshil Mouja 4'],
        tofshiljlnoSA5 = maap['Tofshil JLNO 5'],
        tofshiljaharBs6 = maap['Tofshil Jahar BS 6'],
        tofshilSAkhotianNo7 = maap['Tofshil SA Khotian No 7'],
        tofshilNamzariKhotianNo8 = maap['Tofshil Namzari Khotian No 8'],
        tofshiljaharBSDP9 = maap['Tofshil Jahar BSDP 9'],
        tofshilAdaagNo10 = maap['Tofshil A Daag No 10'],
        tofshiljaharBSchapa11 = maap['Tofshil Jahar BS Chapa 11'],
        tofshiljaharBs12 = maap['Tofshil Jahar BS 12'],
        tofshilMouaji13 = maap['Tofshil Mouaji 13'],
        tofshilchouhaddauttor = maap['Tofshil Chouhadda Uttor'],
        tofshilchouhaddadokshin = maap['Tofshil Chouhadda Dakshin'],
        tofshilchouhaddapurba = maap['Tofshil Chouhadda Purbo'],
        tofshilchouhaddaposchim = maap['Tofshil Chouhadda Poshim'];
}
