import 'package:cloud_firestore/cloud_firestore.dart';

class Files15 {
  double budget;
  String fileid, clientid, clientname, filetype;
  int status,lockunlock;
  List<dynamic> sakkhi = [];
  Timestamp date;
  String descriptionone,
      descriptiontwo,
      registryoffice,
      conpon,
      consompadonertarik,
      contofshilunion0,
      contofshildistrict1,
      contofshilThana2,
      contofshilmouja3,
      contofshiljlnoSA4,
      contofshiljaharBsjl5,
      contofshilStithokhotianNo6,
      contofshilNamzariKhotianNo7,
      contofshilDageMouaji8,
      contofshilMotMouaji9,
      contofshilchouhaddauttor,
      contofshilchouhaddadokshin,
      contofshilchouhaddapurba,
      contofshilchouhaddaposchim,
      consonaktokarinaam,
      consonaktokaripitarnaam,
      consonaktokarimatarnaam,
      consonaktokarigram,
      consonaktokarizila,
      consonaktokaridakghor,
      consonaktokarithana,
      conchotushima7,
      conchotushima8,
      conchotushima9,
      conchotushima10,
      conchotushima11,
      conchotushima12,
      conchotushima13;
  Files15({
    required this.fileid,
    required this.clientid,
    required this.clientname,
    required this.filetype,
    required this.budget,
    required this.registryoffice,
    required this.status,
    required this.date,
    required this.consonaktokarinaam,
    required this.consonaktokaripitarnaam,
    required this.consonaktokarimatarnaam,
    required this.descriptionone,
    required this.descriptiontwo,
    required this.consonaktokarigram,
    required this.consompadonertarik,
    required this.consonaktokaridakghor,
    required this.consonaktokarithana,
    required this.consonaktokarizila,
    required this.conpon,
    required this.sakkhi,
    required this.contofshilchouhaddadokshin,
    required this.contofshilchouhaddaposchim,
    required this.contofshilchouhaddapurba,
    required this.contofshilchouhaddauttor,
    required this.contofshilDageMouaji8,
    required this.contofshildistrict1,
    required this.contofshiljaharBsjl5,
    required this.contofshiljlnoSA4,required this.lockunlock,
    required this.contofshilMotMouaji9,
    required this.contofshilmouja3,
    required this.contofshilNamzariKhotianNo7,
    required this.contofshilStithokhotianNo6,
    required this.contofshilThana2,
    required this.contofshilunion0,
    required this.conchotushima7,
    required this. conchotushima8,
    required this. conchotushima9,
    required this. conchotushima10,
    required this. conchotushima11,
    required this. conchotushima12,
    required this. conchotushima13
  });

  Map<String, dynamic> toMap() => {
        'Files ID': fileid,
        'Client ID': clientid,
        'Client Name': clientname,
        'Description One': descriptionone,
        'Status': status,
        'Budget': budget,
        'Date': date,
        'Files Type': filetype,
        'Description Two': descriptiontwo,
        'Registry Office Naam': registryoffice,
        'Sonaktokarir Naam': consonaktokarinaam,
        'Sonaktokarir Pitar Naam': consonaktokaripitarnaam,
        'Sonaktokarir Matar Naam': consonaktokarimatarnaam,
        'Sonaktokarir Village': consonaktokarigram,
        'Sonaktokarir Post Office': consonaktokaridakghor,
        'Sonaktokarir Thana': consonaktokarithana,
        'Sonaktokarir District': consonaktokarizila,
        'Shomprodaner Tarik': consompadonertarik,
    'Sakkhi': sakkhi,

     'Cotushima 7':conchotushima7,
    'Cotushima 8':conchotushima8,
    'Cotushima 9':conchotushima9,
   'Cotushima 10':conchotushima10,
    'Cotushima 11':conchotushima11,
    'Cotushima 12':conchotushima12,
    'Cotushima 13':conchotushima13,
        'Pon': conpon,
    'LockUnlock':lockunlock,
        'Union': contofshilunion0,
        'Tofshil District 1': contofshildistrict1,
        'Tofshil Thana 2': contofshilThana2,
        'Tofshil Mouja 3': contofshilmouja3,
        'Tofshil JLSA 4': contofshiljlnoSA4,
        'Tofshil BSJL 5': contofshiljaharBsjl5,
        'Tofshil Stitho Khotian 6': contofshilStithokhotianNo6,
        'Tofshil Namzari 7': contofshilNamzariKhotianNo7,
        'Tofshil DageMouaji 8': contofshilDageMouaji8,
        'Tofshil Mot Mouaji 9': contofshilMotMouaji9,
      };

  Files15.fromMap(Map<String, dynamic> maap)
      : fileid = maap['Files ID'],
        clientid = maap['Client ID'],
        clientname = maap['Client Name'],
        descriptionone = maap['Description One'],
        status = maap['Status'],
        consompadonertarik = maap['Shomprodaner Tarik'],
        conpon = maap['Pon'],
        budget = maap['Budget'],
        date = maap['Date'],

        lockunlock = maap["LockUnlock"],
        sakkhi = maap['Sakkhi'],
        conchotushima7 = maap['Cotushima 7'],
        conchotushima8 = maap['Cotushima 8'],
        conchotushima9 = maap['Cotushima 9'],
        conchotushima10 = maap['Cotushima 10'],
        conchotushima11 = maap['Cotushima 11'],
        conchotushima12 = maap['Cotushima 12'],
        conchotushima13 = maap['Cotushima 13'],
        contofshilunion0 = maap['Union'],
        contofshildistrict1 = maap['Tofshil District 1'],
        contofshilThana2 = maap['Tofshil Thana 2'],
        contofshilmouja3 = maap['Tofshil Mouja 3'],
        contofshiljlnoSA4 = maap['Tofshil JLSA 4'],
        contofshiljaharBsjl5 = maap['Tofshil BSJL 5'],
        contofshilStithokhotianNo6 = maap['Tofshil Stitho Khotian 6'],
        contofshilNamzariKhotianNo7 = maap['Tofshil Namzari 7'],
        contofshilDageMouaji8 = maap['Tofshil DageMouaji 8'],
        contofshilMotMouaji9 = maap['Tofshil Mot Mouaji 9'],
        registryoffice = maap['Registry Office Naam'],
        consonaktokarigram = maap['Sonaktokarir Village'],
        consonaktokaridakghor = maap['Sonaktokarir Post Office'],
        consonaktokarithana = maap['Sonaktokarir Thana'],
        consonaktokarizila = maap['Sonaktokarir District'],
        filetype = maap['Files Type'],
        descriptiontwo = maap['Description Two'],
        consonaktokarinaam = maap['Sonaktokarir Naam'],
        consonaktokaripitarnaam = maap['Sonaktokarir Pitar Naam'],
        consonaktokarimatarnaam = maap['Sonaktokarir Matar Naam'],
        contofshilchouhaddauttor = maap['Tofshil Chouhadda Uttor'],
        contofshilchouhaddadokshin = maap['Tofshil Chouhadda Dakshin'],
        contofshilchouhaddapurba = maap['Tofshil Chouhadda Purbo'],
        contofshilchouhaddaposchim = maap['Tofshil Chouhadda Poshim'];
}
